export const REQUEST_MESSAGES_PENDING = "REQUEST_MESSAGES_PENDING";
export const REQUEST_MESSAGES_SUCCESS = "REQUEST_MESSAGES_SUCCESS";
export const REQUEST_MESSAGES_FAIL = "REQUEST_MESSAGES_FAIL";

export const DISPLAY_CARD = "DISPLAY_CARD";
export const CLOSE_CARD = "CLOSE_CARD";

export const SENDING_MESSAGE_PENDING = "SENDING_MESSAGE_PENDING";
export const SENDING_MESSAGE_SUCCES = "SENDING_MESSAGE_SUCCES";

export const GET_CURRENT_POSITION = "GET_CURRENT_POSITION";
export const UPDATE_POSITION = "UPDATE_POSITION";

export const CHANGE_VALUE = "CHANGE_VALUE";
